/**
 * Shopping Center
 * This API provides us with different information about the users to use in the shopping centre to provide a better experience in the visit
 *
 * OpenAPI spec version: 1.0
 * Contact: spilab.uex@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.server.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;



@ApiModel(description = "")
public class Temperature {
  
  @SerializedName("temperature")
  private Double temperature = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getTemperature() {
    return temperature;
  }
  public void setTemperature(Double temperature) {
    this.temperature = temperature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Temperature temperature = (Temperature) o;
    return (this.temperature == null ? temperature.temperature == null : this.temperature.equals(temperature.temperature));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.temperature == null ? 0: this.temperature.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Temperature {\n");
    
    sb.append("  temperature: ").append(temperature).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
